FROM apache/airflow:2.7.1-python3.10

USER root
RUN apt-get update && apt-get install -y git && apt-get clean

USER airflow
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir dvc[http] yfinance pandas mlflow scikit-learn
