FROM apache/airflow:2.7.1-python3.10

USER root
# Install postgres dev headers for psycopg2
RUN apt-get update && apt-get install -y git libpq-dev gcc && apt-get clean

USER airflow
RUN pip install --no-cache-dir --upgrade pip

# Use BuildKit cache mount
COPY requirements.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/home/airflow/.cache/pip \
    pip install --user --upgrade -r /tmp/requirements.txt
